(function () {
  'use strict';
  if (!Auth.requireAuth()) return;
  Auth.renderNav('app-nav');
  var params = new URLSearchParams(location.search), taskId = params.get('task_id'), selectedRunId = params.get('run_id');
  var state = { page: 1, pageSize: 20, total: 0, items: [], task: null, assets: {}, resultPage: 1, resultPageSize: 20, allResults: [], filteredResults: [] };
  var error = document.getElementById('page-error'), detailModal = new bootstrap.Modal(document.getElementById('detailModal'));
  function escapeHtml(v) { return v == null ? '' : String(v).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;'); }
  function showError(msg) { error.textContent = msg; error.classList.remove('d-none'); } function hideError() { error.classList.add('d-none'); error.textContent = ''; }
  function formatTime(value) { if (!value) return '-'; var d = new Date(value); return isNaN(d.getTime()) ? escapeHtml(value) : d.toLocaleString('zh-CN', { hour12: false }); }
  function runClass(status) { return { completed: 'status-success', failed: 'status-failed', running: 'status-running', pending: 'status-pending' }[status] || 'status-unknown'; } function runLabel(status) { return { completed: '已完成', failed: '失败', running: '运行中', pending: '排队中' }[status] || status || '-'; }
  function resultClass(status) { return { success: 'status-success', warning: 'status-warning', failed: 'status-failed' }[status] || 'status-unknown'; } function resultLabel(status) { return { success: '成功', warning: '警告', failed: '失败' }[status] || status || '-'; } function typeLabel(type) { return { ping: 'Ping', port: '端口', http: 'HTTP' }[type] || type || '-'; }
  function pagination() { var pages = Math.max(1, Math.ceil(state.total / state.pageSize)); document.getElementById('runs-page-info').textContent = '共 ' + state.total + ' 条 | 第 ' + state.page + '/' + pages + ' 页'; document.getElementById('runs-prev').disabled = state.page <= 1; document.getElementById('runs-next').disabled = state.total === 0 || state.page >= pages; }
  function renderSummary() { if (!state.task) return; document.getElementById('run-summary').innerHTML = '<div class="col-md-4"><div class="stat-card"><div class="stat-icon"><i class="bi bi-clipboard-check"></i></div><div><div class="stat-label">任务名称</div><div class="fw-semibold">' + escapeHtml(state.task.name) + '</div></div></div></div><div class="col-md-4"><div class="stat-card"><div class="stat-icon"><i class="bi bi-list-check"></i></div><div><div class="stat-label">检测类型</div><div>' + escapeHtml((state.task.check_types || []).join('、')) + '</div></div></div></div><div class="col-md-4"><div class="stat-card"><div class="stat-icon"><i class="bi bi-hdd-stack"></i></div><div><div class="stat-label">巡检资产</div><div class="stat-value">' + escapeHtml((state.task.asset_ids || []).length) + '</div></div></div></div>'; }
  async function loadTask() { if (!taskId) { showError('缺少任务参数，请从巡检任务页面进入。'); document.getElementById('run-summary').innerHTML = ''; return false; } try { state.task = await api.get('/api/tasks/' + encodeURIComponent(taskId)); renderSummary(); return true; } catch (err) { showError('加载任务失败：' + err.message); return false; } }
  async function loadAssets() { try { var data = await api.get('/api/assets?page=1&page_size=100'); (data && data.items || []).forEach(function (asset) { state.assets[String(asset.id)] = asset.name || asset.ip || ('资产 #' + asset.id); }); } catch (err) {} }
  async function loadRuns() { if (!taskId) return; var tbody = document.getElementById('runs-tbody'); tbody.innerHTML = '<tr><td colspan="6" class="text-center text-muted py-4">加载中...</td></tr>'; try { var data = await api.get('/api/tasks/' + encodeURIComponent(taskId) + '/runs?page=' + state.page + '&page_size=' + state.pageSize); state.total = data && data.total || 0; var items = data && data.items || []; state.items = items; if (!selectedRunId && items.length) selectedRunId = String(items[0].id); tbody.innerHTML = items.length ? items.map(function (run) { return '<tr class="' + (String(run.id) === String(selectedRunId) ? 'table-active' : '') + '"><td>' + escapeHtml(run.id) + '</td><td><span class="status-badge ' + runClass(run.status) + '">' + escapeHtml(runLabel(run.status)) + '</span></td><td>' + formatTime(run.started_at) + '</td><td>' + formatTime(run.finished_at) + '</td><td class="text-truncate-cell" title="' + escapeHtml(run.error_message || '') + '">' + escapeHtml(run.error_message || '-') + '</td><td class="text-end"><button class="btn btn-sm btn-outline-primary js-view-run" data-id="' + escapeHtml(run.id) + '">查看结果</button></td></tr>'; }).join('') : '<tr><td colspan="6" class="empty-state"><i class="bi bi-clock-history"></i><div>暂无运行记录</div></td></tr>'; pagination(); if (selectedRunId) loadResults(); } catch (err) { tbody.innerHTML = ''; state.total = 0; pagination(); showError('加载运行记录失败：' + err.message); } }
  async function loadResults() { var placeholder = document.getElementById('results-placeholder'), content = document.getElementById('results-content'); placeholder.textContent = '加载运行结果中...'; placeholder.classList.remove('d-none'); content.classList.add('d-none'); try { var data = await api.get('/api/tasks/runs/' + encodeURIComponent(selectedRunId) + '/results?page=1&page_size=200'); state.allResults = data && data.items || []; state.resultPage = 1; filterResults(); placeholder.classList.add('d-none'); content.classList.remove('d-none'); document.getElementById('current-run-text').textContent = '(运行 #' + selectedRunId + ')'; var diagnosisLink = document.getElementById('open-diagnosis'); diagnosisLink.href = 'diagnosis.html?run_id=' + encodeURIComponent(selectedRunId); diagnosisLink.classList.remove('d-none'); var link = document.getElementById('open-results'); link.href = 'results.html?run_id=' + encodeURIComponent(selectedRunId); link.classList.remove('d-none'); } catch (err) { showError('加载运行结果失败：' + err.message); placeholder.textContent = '运行结果加载失败。'; } }
  function filterResults() { var type = document.getElementById('rf-type').value, status = document.getElementById('rf-status').value; state.filteredResults = state.allResults.filter(function (item) { return (!type || item.check_type === type) && (!status || item.status === status); }); renderResults(); }
  function renderResults() { var start = (state.resultPage - 1) * state.resultPageSize, items = state.filteredResults.slice(start, start + state.resultPageSize), tbody = document.getElementById('result-tbody'); tbody.innerHTML = items.length ? items.map(function (item, index) { var text = item.error_message || item.message || '-'; return '<tr><td>' + escapeHtml(state.assets[String(item.asset_id)] || ('资产 #' + item.asset_id)) + '</td><td>' + escapeHtml(typeLabel(item.check_type)) + '</td><td><span class="status-badge ' + resultClass(item.status) + '">' + escapeHtml(resultLabel(item.status)) + '</span></td><td>' + (item.response_time == null ? '-' : escapeHtml(item.response_time) + ' ms') + '</td><td class="text-truncate-cell" title="' + escapeHtml(text) + '">' + escapeHtml(text) + '</td><td>' + formatTime(item.checked_at) + '</td><td class="text-end"><button class="btn btn-sm btn-outline-primary js-detail" data-index="' + (start + index) + '">详情</button></td></tr>'; }).join('') : '<tr><td colspan="7" class="empty-state"><i class="bi bi-inbox"></i><div>暂无符合条件的结果</div></td></tr>'; var pages = Math.max(1, Math.ceil(state.filteredResults.length / state.resultPageSize)); document.getElementById('result-page-info').textContent = '共 ' + state.filteredResults.length + ' 条 | 第 ' + state.resultPage + '/' + pages + ' 页'; document.getElementById('result-prev').disabled = state.resultPage <= 1; document.getElementById('result-next').disabled = state.filteredResults.length === 0 || state.resultPage >= pages; }
  function showDetail(item) { var rows = [['结果 ID', item.id], ['运行 ID', item.run_id], ['资产', state.assets[String(item.asset_id)] || ('资产 #' + item.asset_id)], ['检测类型', typeLabel(item.check_type)], ['目标', item.target], ['状态', resultLabel(item.status)], ['响应耗时', item.response_time == null ? null : item.response_time + ' ms'], ['消息', item.message], ['错误信息', item.error_message], ['检测时间', formatTime(item.checked_at)]]; document.getElementById('detail-content').innerHTML = rows.map(function (row) { return '<dt class="col-sm-3">' + escapeHtml(row[0]) + '</dt><dd class="col-sm-9 text-break">' + escapeHtml(row[1] == null || row[1] === '' ? '-' : row[1]) + '</dd>'; }).join(''); detailModal.show(); }
  document.getElementById('runs-tbody').addEventListener('click', function (event) { var button = event.target.closest('.js-view-run'); if (!button) return; selectedRunId = button.getAttribute('data-id'); history.replaceState(null, '', 'task-run.html?task_id=' + encodeURIComponent(taskId) + '&run_id=' + encodeURIComponent(selectedRunId)); loadRuns(); }); document.getElementById('result-tbody').addEventListener('click', function (event) { var button = event.target.closest('.js-detail'); if (button) showDetail(state.filteredResults[Number(button.getAttribute('data-index'))]); }); document.getElementById('result-filter').addEventListener('submit', function (event) { event.preventDefault(); state.resultPage = 1; filterResults(); }); document.getElementById('result-reset').addEventListener('click', function () { document.getElementById('rf-type').value = ''; document.getElementById('rf-status').value = ''; state.resultPage = 1; filterResults(); }); document.getElementById('result-prev').addEventListener('click', function () { if (state.resultPage > 1) { state.resultPage--; renderResults(); } }); document.getElementById('result-next').addEventListener('click', function () { if (state.resultPage < Math.ceil(state.filteredResults.length / state.resultPageSize)) { state.resultPage++; renderResults(); } }); document.getElementById('runs-prev').addEventListener('click', function () { if (state.page > 1) { state.page--; loadRuns(); } }); document.getElementById('runs-next').addEventListener('click', function () { if (state.page < Math.ceil(state.total / state.pageSize)) { state.page++; loadRuns(); } }); document.getElementById('btn-refresh').addEventListener('click', function () { hideError(); loadTask(); loadAssets(); loadRuns(); });
  // 巡检执行为异步，若最近一次运行仍在处理中则自动轮询刷新，避免用户手动刷新
  var pollTimer = setInterval(function () {
    var visible = state.items || [];
    var active = visible.filter(function (r) { return r.status === 'pending' || r.status === 'running'; });
    if (!active.length) { clearInterval(pollTimer); return; }
    loadRuns();
  }, 2000);
  loadAssets().then(function () { loadTask().then(function (loaded) { if (loaded) loadRuns(); }); });
})();
