(function () {
  'use strict';
  if (!Auth.requireAuth()) return;
  Auth.renderNav('app-nav');
  var state = { page: 1, pageSize: 20, total: 0, items: [], assets: [] };
  var tbody = document.getElementById('task-tbody');
  var listError = document.getElementById('list-error');
  var modal = new bootstrap.Modal(document.getElementById('taskModal'));
  var CHECK_TYPES = ['ping', 'port', 'http', 'dns'];
  function escapeHtml(value) { return value == null ? '' : String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;'); }
  function showError(el, message) { el.textContent = message; el.classList.remove('d-none'); }
  function hideError(el) { el.textContent = ''; el.classList.add('d-none'); }
  function checkLabel(type) { return { ping: 'Ping', port: '端口', http: 'HTTP', dns: 'DNS' }[type] || type; }
  function fmtTime(value) { if (!value) return '-'; var date = new Date(value); return isNaN(date.getTime()) ? escapeHtml(value) : date.toLocaleString('zh-CN', { hour12: false }); }
  function renderPagination() { var pages = Math.max(1, Math.ceil(state.total / state.pageSize)); document.getElementById('page-info').textContent = '共 ' + state.total + ' 条 | 第 ' + state.page + '/' + pages + ' 页'; document.getElementById('btn-prev').disabled = state.page <= 1; document.getElementById('btn-next').disabled = state.total === 0 || state.page >= pages; }
  function renderTasks() {
    if (!state.items.length) { tbody.innerHTML = '<tr><td colspan="11" class="empty-state"><i class="bi bi-inbox"></i><div>暂无巡检任务</div></td></tr>'; return; }
    tbody.innerHTML = state.items.map(function (task) {
      var types = (task.check_types || []).map(function (type) { return '<span class="badge text-bg-light border me-1">' + escapeHtml(checkLabel(type)) + '</span>'; }).join('') || '-';
      var scheduleOn = !!task.schedule_enabled;
      var scheduleText = scheduleOn ? '已启用' : '未启用';
      var interval = task.schedule_interval_minutes ? escapeHtml(task.schedule_interval_minutes) + ' 分钟' : '-';
      return '<tr><td>' + escapeHtml(task.id) + '</td><td>' + escapeHtml(task.name) + '</td><td>' + types + '</td><td>' + escapeHtml((task.asset_ids || []).length) + '</td><td><span class="status-badge ' + (task.enabled ? 'status-success' : 'status-disabled') + '">' + (task.enabled ? '已启用' : '已停用') + '</span></td><td><span class="status-badge ' + (scheduleOn ? 'status-running' : 'status-disabled') + '">' + scheduleText + '</span></td><td class="text-nowrap">' + interval + '</td><td class="text-nowrap">' + fmtTime(task.next_run_at) + '</td><td class="text-nowrap">' + fmtTime(task.last_scheduled_run_at) + '</td><td class="text-truncate-cell" title="' + escapeHtml(task.description || '') + '">' + escapeHtml(task.description || '-') + '</td><td class="text-end text-nowrap"><button class="btn btn-sm btn-outline-primary btn-icon me-1 js-edit" data-id="' + escapeHtml(task.id) + '" title="编辑"><i class="bi bi-pencil"></i></button><button class="btn btn-sm btn-outline-' + (task.enabled ? 'secondary' : 'success') + ' btn-icon me-1 js-toggle" data-id="' + escapeHtml(task.id) + '" title="' + (task.enabled ? '停用' : '启用') + '"><i class="bi bi-' + (task.enabled ? 'pause' : 'play') + '"></i></button><button class="btn btn-sm btn-outline-danger btn-icon me-1 js-run" data-id="' + escapeHtml(task.id) + '" title="立即执行"><i class="bi bi-play-fill"></i></button><a class="btn btn-sm btn-outline-secondary btn-icon js-runs" href="task-run.html?task_id=' + encodeURIComponent(task.id) + '" title="运行记录"><i class="bi bi-clock-history"></i></a></td></tr>';
    }).join('');
  }
  async function loadTasks() { hideError(listError); tbody.innerHTML = '<tr><td colspan="11" class="text-center text-muted py-4">加载中...</td></tr>'; try { var data = await api.get('/api/tasks?page=' + state.page + '&page_size=' + state.pageSize); state.total = data && data.total || 0; state.items = data && data.items || []; renderTasks(); } catch (err) { state.total = 0; state.items = []; tbody.innerHTML = ''; showError(listError, '加载巡检任务失败：' + err.message); } renderPagination(); }
  async function loadAssets() { var select = document.getElementById('m-assets'); try { var data = await api.get('/api/assets?page=1&page_size=100'); state.assets = data && data.items || []; select.innerHTML = state.assets.map(function (asset) { return '<option value="' + escapeHtml(asset.id) + '">' + escapeHtml(asset.name || asset.ip || ('资产 #' + asset.id)) + (asset.ip ? ' (' + escapeHtml(asset.ip) + ')' : '') + '</option>'; }).join(''); document.getElementById('asset-help').textContent = state.assets.length ? '按住 Ctrl 或 Shift 可多选。' : '当前没有可选资产，请先在资产管理中新增资产。'; } catch (err) { state.assets = []; select.innerHTML = ''; document.getElementById('asset-help').textContent = '资产加载失败：' + err.message; showError(document.getElementById('form-error'), '加载资产失败：' + err.message); } }
  function selectedTypes() { return Array.prototype.slice.call(document.querySelectorAll('input[id^="check-"]:checked')).map(function (input) { return input.value; }); }
  function setSelectedAssets(ids) { var chosen = (ids || []).map(String); Array.prototype.slice.call(document.getElementById('m-assets').options).forEach(function (option) { option.selected = chosen.indexOf(option.value) !== -1; }); }
  function syncScheduleInput() { var enabled = document.getElementById('m-schedule-enabled').checked; document.getElementById('m-schedule-interval').disabled = !enabled; }
  async function openModal(task) {
    document.getElementById('task-form').reset(); hideError(document.getElementById('form-error')); document.getElementById('task-id').value = task ? task.id : ''; document.getElementById('taskModalLabel').textContent = task ? '编辑巡检任务' : '新建巡检任务'; document.getElementById('save-text').textContent = task ? '保存' : '新建';
    CHECK_TYPES.forEach(function (type) { var el = document.getElementById('check-' + type); if (el) el.checked = type === 'ping'; });
    document.getElementById('m-schedule-enabled').checked = false; document.getElementById('m-schedule-interval').value = '';
    if (task) { document.getElementById('m-name').value = task.name || ''; document.getElementById('m-description').value = task.description || ''; document.getElementById('m-enabled').checked = !!task.enabled; CHECK_TYPES.forEach(function (type) { var el = document.getElementById('check-' + type); if (el) el.checked = (task.check_types || []).indexOf(type) !== -1; }); document.getElementById('m-schedule-enabled').checked = !!task.schedule_enabled; document.getElementById('m-schedule-interval').value = task.schedule_interval_minutes || ''; }
    syncScheduleInput(); modal.show(); await loadAssets(); if (task) setSelectedAssets(task.asset_ids);
  }
  document.getElementById('m-schedule-enabled').addEventListener('change', syncScheduleInput);
  document.getElementById('btn-create').addEventListener('click', function () { openModal(null); });
  document.getElementById('task-form').addEventListener('submit', async function (event) { event.preventDefault(); var formError = document.getElementById('form-error'); hideError(formError); var assetIds = Array.prototype.slice.call(document.getElementById('m-assets').selectedOptions).map(function (option) { return Number(option.value); }); var scheduleEnabled = document.getElementById('m-schedule-enabled').checked; var intervalText = document.getElementById('m-schedule-interval').value; var interval = intervalText ? Number(intervalText) : null; var body = { name: document.getElementById('m-name').value.trim(), description: document.getElementById('m-description').value.trim() || null, check_types: selectedTypes(), asset_ids: assetIds, enabled: document.getElementById('m-enabled').checked, schedule_enabled: scheduleEnabled, schedule_interval_minutes: interval }; if (!body.name) return showError(formError, '请填写任务名称'); if (!body.check_types.length) return showError(formError, '请至少选择一种检测类型'); if (!body.asset_ids.length) return showError(formError, '请至少选择一个资产'); if (scheduleEnabled && (!interval || interval < 1)) return showError(formError, '启用定时巡检时，间隔分钟必须大于 0'); var id = document.getElementById('task-id').value; var button = document.getElementById('btn-save'); button.disabled = true; document.getElementById('save-spin').classList.remove('d-none'); try { if (id) await api.put('/api/tasks/' + encodeURIComponent(id), body); else await api.post('/api/tasks', body); modal.hide(); state.page = id ? state.page : 1; loadTasks(); } catch (err) { showError(formError, '保存失败：' + err.message); } finally { button.disabled = false; document.getElementById('save-spin').classList.add('d-none'); } });
  tbody.addEventListener('click', async function (event) { var button = event.target.closest('button'); if (!button) return; var task = state.items.filter(function (item) { return String(item.id) === button.getAttribute('data-id'); })[0]; if (!task) return; if (button.classList.contains('js-edit')) openModal(task); else if (button.classList.contains('js-toggle')) { try { await api.post('/api/tasks/' + encodeURIComponent(task.id) + '/' + (task.enabled ? 'disable' : 'enable')); loadTasks(); } catch (err) { showError(listError, '更新任务状态失败：' + err.message); } } else if (button.classList.contains('js-run')) { button.disabled = true; try { var run = await api.post('/api/tasks/' + encodeURIComponent(task.id) + '/run'); location.href = 'task-run.html?task_id=' + encodeURIComponent(task.id) + '&run_id=' + encodeURIComponent(run.id); } catch (err) { button.disabled = false; showError(listError, '执行任务失败：' + err.message); } } });
  document.getElementById('btn-prev').addEventListener('click', function () { if (state.page > 1) { state.page--; loadTasks(); } }); document.getElementById('btn-next').addEventListener('click', function () { if (state.page < Math.ceil(state.total / state.pageSize)) { state.page++; loadTasks(); } });
  loadTasks();
})();
